# Conda environment configuration for the Versatile-RL-PyTorch project
# To create this environment, run: conda env create -f environment.yml
# To update this environment, run: conda env update --file environment.yml --prune

name: rl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8      # needs compatible NVIDIA driver
  - gymnasium=1.2.*
  - box2d-py               # LunarLander physics
  - stable-baselines3=2.7.0
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - tqdm
  - moviepy
  - imageio-ffmpeg         # for video export
